### ISSUE TITLE
Error is shown in the title of the title of the xslt trace report in ladybug

### ISSUE THREAD

**Issue by MarkvdVorst** [wearefrank/xslt-debugger-webapp#19]
![image](https://github.com/wearefrank/xslt-debugger-webapp/assets/34445874/ffc027a2-ad94-4666-adf1-0277e685a3d5)
A stacktrace is shown in the first startpoint of the trace report.

This should not be shown and generally for the demo it would be nice if this one is removed as it does not add any  context to the report.

I suspect there might be an extra unnecessary start-/endpoint in the webapp that stores the stacktrace in the title.

**Comment by Matthbo** [comment]
This still exists and seems to be happening to every inputted xsl file.
Seems like the Saxon implementation is broken because 'The prefix "xsl" for element "xsl:template" is not bound.' makes it seem as if the xsl namespace isn't even available properly 

XML input
```xml
<Configuration>
	<Adapter name="XmlSwitchExample">
		<Receiver name="XmlSwitchReceiver">
			<ApiListener
				name="XmlSwitchListener"
				uriPattern="/xmlswitch"
				method="POST"/>
		</Receiver>

		<Pipeline>
			<Exits>
				<Exit name="EXIT" state="SUCCESS" />
				<Exit name="ERROR" state="ERROR"/>
			</Exits>

			<XmlSwitchPipe name="RouteByRootElement" notFoundForwardName="exception" >
				<Forward name="success" path="EXIT"/>
				<Forward name="exception" path="ERROR"/>
			</XmlSwitchPipe>
		</Pipeline>
	</Adapter>
</Configuration>
```

Stacktrace of [adapter2mermaid.xsl](https://github.com/frankframework/frankframework/blob/c5bfe835e7c2ac4f9558e3db63f626eb9341156a/core/src/main/resources/xml/xsl/adapter2mermaid.xsl):
```
Could not transform report xml: org.xml.sax.SAXParseException; lineNumber: 46; columnNumber: 166; The prefix "xsl" for element "xsl:template" is not bound.

Stacktrace:
net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 46; columnNumber: 166; The prefix "xsl" for element "xsl:template" is not bound.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:459)
	at net.sf.saxon.event.Sender.send(Sender.java:168)
	at net.sf.saxon.Controller.makeSourceTree(Controller.java:1320)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:335)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:74)
	at nl.nn.testtool.transform.ReportXmlTransformer.transform(ReportXmlTransformer.java:122)
	at nl.nn.testtool.Report.toXml(Report.java:975)
	at nl.nn.testtool.Report.toXml(Report.java:889)
	at nl.nn.testtool.web.api.ReportApi.getReport(ReportApi.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at nl.nn.testtool.web.ApiServlet.doRequest(ApiServlet.java:142)
	at nl.nn.testtool.web.ApiServlet.doGet(ApiServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:641)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:415)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:347)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:284)
	at nl.nn.testtool.web.ApiServlet.doRequest(ApiServlet.java:128)
	at nl.nn.testtool.web.ApiServlet.doGet(ApiServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 46; columnNumber: 166; The prefix "xsl" for element "xsl:template" is not bound.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	... 64 more
---------
org.xml.sax.SAXParseException; lineNumber: 46; columnNumber: 166; The prefix "xsl" for element "xsl:template" is not bound.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	at net.sf.saxon.event.Sender.send(Sender.java:168)
	at net.sf.saxon.Controller.makeSourceTree(Controller.java:1320)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:335)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:74)
	at nl.nn.testtool.transform.ReportXmlTransformer.transform(ReportXmlTransformer.java:122)
	at nl.nn.testtool.Report.toXml(Report.java:975)
	at nl.nn.testtool.Report.toXml(Report.java:889)
	at nl.nn.testtool.web.api.ReportApi.getReport(ReportApi.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at nl.nn.testtool.web.ApiServlet.doRequest(ApiServlet.java:142)
	at nl.nn.testtool.web.ApiServlet.doGet(ApiServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:641)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:415)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:347)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:284)
	at nl.nn.testtool.web.ApiServlet.doRequest(ApiServlet.java:128)
	at nl.nn.testtool.web.ApiServlet.doGet(ApiServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:383)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:936)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)

First 7584 characters of xml to transform:
<Report Name="Saxon Example Report 2" Description="" Path="" CorrelationId="98db970c-2152-4490-9cc8-6f0c9a3afea1" StartTime="1771808990378" EndTime="1771808990398" NumberOfCheckpoints="22" EstimatedMemoryUsage="8446"><Checkpoint Name="Saxon Example Report 2" Type="Startpoint" Level="0">XSLT Trace</Checkpoint><Checkpoint Name="Start XSLT" Type="Startpoint" Level="1" SourceClassName="xsltExample2.xml">Start XSLT</Checkpoint><Checkpoint Name="XML input" Type="Infopoint" Level="2"><test>
    <bla/>
    <die/>
    <bla/>
</test></Checkpoint><Checkpoint Name="XSL input" Type="Infopoint" Level="2" SourceClassName="xsltExample2.xml"><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output indent="yes"/>
    <xsl:template match="*|@*|comment()|processing-instruction()|text()">
        <xsl:copy>
            <xsl:apply-templates select="*|@*|comment()|processing-instruction()|text()"/>
        </xsl:copy>
    </xsl:template>
</xsl:stylesheet></Checkpoint><Checkpoint Name="Complete XSLT Trace" Type="Infopoint" Level="2" SourceClassName="xsltExample2.xsl">--------------------------------------------New trace instruction being applied--------------------------------------------
&lt;trace saxon-version=&quot;10.8&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
&lt;/trace&gt;
--------------------------------------------New trace instruction being applied--------------------------------------------
&lt;source node=&quot;/test&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test --&gt;
--------------------------------------------New trace instruction being applied--------------------------------------------
&lt;source node=&quot;/test/bla[1]&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test/bla[1] --&gt;
--------------------------------------------New trace instruction being applied--------------------------------------------
&lt;source node=&quot;/test/die[1]&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test/die[1] --&gt;
--------------------------------------------New trace instruction being applied--------------------------------------------
&lt;source node=&quot;/test/bla[2]&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test/bla[2] --&gt;
</Checkpoint><Checkpoint Name="XML after full transformation" Type="Infopoint" Level="2" SourceClassName="xsltExample2.xml" TextDecl="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;">
<test>
   <bla/>
   <die/>
   <bla/>
</test>
</Checkpoint><Checkpoint Name="Trace layout" Type="Startpoint" Level="2" Null="true"/><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Startpoint" Level="3" SourceClassName="3_74_"><test>
    <bla/>
    <die/>
    <bla/>
</test>

    
    
    
</Checkpoint><Checkpoint Name="Line #3 Column #74: xsltExample2.xsl" Type="Infopoint" Level="4"><xsl:template match="*|@*|comment()|processing-instruction()|text()">
        <xsl:copy>
            <xsl:apply-templates select="*|@*|comment()|processing-instruction()|text()"/>
        </xsl:copy>
    </xsl:template>
</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Startpoint" Level="4" SourceClassName="3_74_"><test>
    <bla/>
    <die/>
    <bla/>
</test>

    
    
    
</Checkpoint><Checkpoint Name="Line #3 Column #74: xsltExample2.xsl" Type="Infopoint" Level="5"><xsl:template match="*|@*|comment()|processing-instruction()|text()">
        <xsl:copy>
            <xsl:apply-templates select="*|@*|comment()|processing-instruction()|text()"/>
        </xsl:copy>
    </xsl:template>
</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Endpoint" Level="5" SourceClassName="3_74_">&lt;source node=&quot;/test/bla[1]&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test/bla[1] --&gt;</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Startpoint" Level="4" SourceClassName="3_74_"><test>
    <bla/>
    <die/>
    <bla/>
</test>

    
    
    
</Checkpoint><Checkpoint Name="Line #3 Column #74: xsltExample2.xsl" Type="Infopoint" Level="5"><xsl:template match="*|@*|comment()|processing-instruction()|text()">
        <xsl:copy>
            <xsl:apply-templates select="*|@*|comment()|processing-instruction()|text()"/>
        </xsl:copy>
    </xsl:template>
</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Endpoint" Level="5" SourceClassName="3_74_">&lt;source node=&quot;/test/die[1]&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test/die[1] --&gt;</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Startpoint" Level="4" SourceClassName="3_74_"><test>
    <bla/>
    <die/>
    <bla/>
</test>

    
    
    
</Checkpoint><Checkpoint Name="Line #3 Column #74: xsltExample2.xsl" Type="Infopoint" Level="5"><xsl:template match="*|@*|comment()|processing-instruction()|text()">
        <xsl:copy>
            <xsl:apply-templates select="*|@*|comment()|processing-instruction()|text()"/>
        </xsl:copy>
    </xsl:template>
</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Endpoint" Level="5" SourceClassName="3_74_">&lt;source node=&quot;/test/bla[2]&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test/bla[2] --&gt;</Checkpoint><Checkpoint Name="template match=*|@*|comment()|processing-instruction()|text()" Type="Endpoint" Level="4" SourceClassName="3_74_">&lt;source node=&quot;/test&quot; file=&quot;file:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/xsltExample2.xml&quot;&gt;
&lt;xsl:template match=*|@*|comment()|processing-instruction()|text()  line=&quot;3&quot; column=&quot;74&quot; module=&quot;&quot;&gt;
&lt;/source&gt;&lt;!-- /test --&gt;</Checkpoint><Checkpoint Name="Trace layout" Type="Endpoint" Level="3" Null="true"/><Checkpoint Name="Start XSLT" Type="Endpoint" Level="2" SourceClassName="xsltExample2.xml">End of XSLT</Checkpoint><Checkpoint Name="Saxon Example Report 2" Type="Endpoint" Level="1">XSLT Trace</Checkpoint></Report>
```
